### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by channgli** [subeeshcbabu/swagmock#45]
Hello ,
Can help to look at the this install issue.
LM-SHC-16502628:swagmock qiangli3$ npm install swagmock
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "swagmock"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install swagmock as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qiangli3/work/swagger/swagmock/npm-debug.log

**Comment by subeeshcbabu-zz** [comment]
probably named the project `swagmock` and NPM did not like it?
Saw this post and this might be related - http://thisdavej.com/node-newbie-error-npm-refusing-to-install-package-as-a-dependency-of-itself/

**Comment by channgli** [comment]
Thanks, i know that , but i still have other issue ,will create new one
